#!/usr/bin/env bash
# This script installs nginx on a new Ubuntu machine and configures it to meet the specified requirements.

# installs nginx and changes default html file
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
