#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set variables
SERVER_HOSTNAME=$(hostname)

# Configure Nginx to add custom header
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

