#!/bin/env bash

# Check if the script is called with an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 $ip_address
