#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo bash -c "echo $$ > /var/run/myscript.pid"

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me"' SIGINT
trap 'rm -f /var/run/myscript.pid' SIGQUIT
echo $$ > /var/run/myscript.pid

# display 'To infinity and beyond' indefinately
while true
do
    echo 'To infinity and beyond'
    sleep 2
done
